/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssuranceRouteImport } from './routes/assurance'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as CredentialRouteImport } from './routes/credential'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as PackRouteImport } from './routes/pack'
import { Route as RemediationRouteImport } from './routes/remediation'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as CasesIndexRouteImport } from './routes/cases/index'
import { Route as CasesIdRouteImport } from './routes/cases/$id'
import { Route as VendorsIndexRouteImport } from './routes/vendors/index'
import { Route as VendorsIdRouteImport } from './routes/vendors/$id'
import { Route as WorkerIndexRouteImport } from './routes/worker/index'
import { Route as WorkerSubmitRouteImport } from './routes/worker/submit'
import { Route as WorkerCaseCodeRouteImport } from './routes/worker/case.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceRoute = AssuranceRouteImport.update({
  id: '/assurance',
  path: '/assurance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialRoute = CredentialRouteImport.update({
  id: '/credential',
  path: '/credential',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const PackRoute = PackRouteImport.update({
  id: '/pack',
  path: '/pack',
  getParentRoute: () => rootRouteImport,
} as any)
const RemediationRoute = RemediationRouteImport.update({
  id: '/remediation',
  path: '/remediation',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIdRoute = CasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIdRoute = VendorsIdRouteImport.update({
  id: '/vendors/$id',
  path: '/vendors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerIndexRoute = WorkerIndexRouteImport.update({
  id: '/worker/',
  path: '/worker/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerSubmitRoute = WorkerSubmitRouteImport.update({
  id: '/worker/submit',
  path: '/worker/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerCaseCodeRoute = WorkerCaseCodeRouteImport.update({
  id: '/worker/case/$code',
  path: '/worker/case/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assurance': typeof AssuranceRoute
  '/audit': typeof AuditRoute
  '/credential': typeof CredentialRoute
  '/dashboard': typeof DashboardRoute
  '/evidence': typeof EvidenceRoute
  '/pack': typeof PackRoute
  '/remediation': typeof RemediationRoute
  '/reset': typeof ResetRoute
  '/verification': typeof VerificationRoute
  '/verify': typeof VerifyRoute
  '/cases/$id': typeof CasesIdRoute
  '/vendors/$id': typeof VendorsIdRoute
  '/worker/submit': typeof WorkerSubmitRoute
  '/cases/': typeof CasesIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/worker/': typeof WorkerIndexRoute
  '/worker/case/$code': typeof WorkerCaseCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assurance': typeof AssuranceRoute
  '/audit': typeof AuditRoute
  '/credential': typeof CredentialRoute
  '/dashboard': typeof DashboardRoute
  '/evidence': typeof EvidenceRoute
  '/pack': typeof PackRoute
  '/remediation': typeof RemediationRoute
  '/reset': typeof ResetRoute
  '/verification': typeof VerificationRoute
  '/verify': typeof VerifyRoute
  '/cases/$id': typeof CasesIdRoute
  '/vendors/$id': typeof VendorsIdRoute
  '/worker/submit': typeof WorkerSubmitRoute
  '/cases': typeof CasesIndexRoute
  '/vendors': typeof VendorsIndexRoute
  '/worker': typeof WorkerIndexRoute
  '/worker/case/$code': typeof WorkerCaseCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assurance': typeof AssuranceRoute
  '/audit': typeof AuditRoute
  '/credential': typeof CredentialRoute
  '/dashboard': typeof DashboardRoute
  '/evidence': typeof EvidenceRoute
  '/pack': typeof PackRoute
  '/remediation': typeof RemediationRoute
  '/reset': typeof ResetRoute
  '/verification': typeof VerificationRoute
  '/verify': typeof VerifyRoute
  '/cases/$id': typeof CasesIdRoute
  '/vendors/$id': typeof VendorsIdRoute
  '/worker/submit': typeof WorkerSubmitRoute
  '/cases/': typeof CasesIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/worker/': typeof WorkerIndexRoute
  '/worker/case/$code': typeof WorkerCaseCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assurance'
    | '/audit'
    | '/credential'
    | '/dashboard'
    | '/evidence'
    | '/pack'
    | '/remediation'
    | '/reset'
    | '/verification'
    | '/verify'
    | '/cases/$id'
    | '/vendors/$id'
    | '/worker/submit'
    | '/cases/'
    | '/vendors/'
    | '/worker/'
    | '/worker/case/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assurance'
    | '/audit'
    | '/credential'
    | '/dashboard'
    | '/evidence'
    | '/pack'
    | '/remediation'
    | '/reset'
    | '/verification'
    | '/verify'
    | '/cases/$id'
    | '/vendors/$id'
    | '/worker/submit'
    | '/cases'
    | '/vendors'
    | '/worker'
    | '/worker/case/$code'
  id:
    | '__root__'
    | '/'
    | '/assurance'
    | '/audit'
    | '/credential'
    | '/dashboard'
    | '/evidence'
    | '/pack'
    | '/remediation'
    | '/reset'
    | '/verification'
    | '/verify'
    | '/cases/$id'
    | '/vendors/$id'
    | '/worker/submit'
    | '/cases/'
    | '/vendors/'
    | '/worker/'
    | '/worker/case/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssuranceRoute: typeof AssuranceRoute
  AuditRoute: typeof AuditRoute
  CredentialRoute: typeof CredentialRoute
  DashboardRoute: typeof DashboardRoute
  EvidenceRoute: typeof EvidenceRoute
  PackRoute: typeof PackRoute
  RemediationRoute: typeof RemediationRoute
  ResetRoute: typeof ResetRoute
  VerificationRoute: typeof VerificationRoute
  VerifyRoute: typeof VerifyRoute
  CasesIdRoute: typeof CasesIdRoute
  VendorsIdRoute: typeof VendorsIdRoute
  WorkerSubmitRoute: typeof WorkerSubmitRoute
  CasesIndexRoute: typeof CasesIndexRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
  WorkerIndexRoute: typeof WorkerIndexRoute
  WorkerCaseCodeRoute: typeof WorkerCaseCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance': {
      id: '/assurance'
      path: '/assurance'
      fullPath: '/assurance'
      preLoaderRoute: typeof AssuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credential': {
      id: '/credential'
      path: '/credential'
      fullPath: '/credential'
      preLoaderRoute: typeof CredentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pack': {
      id: '/pack'
      path: '/pack'
      fullPath: '/pack'
      preLoaderRoute: typeof PackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remediation': {
      id: '/remediation'
      path: '/remediation'
      fullPath: '/remediation'
      preLoaderRoute: typeof RemediationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$id': {
      id: '/cases/$id'
      path: '/cases/$id'
      fullPath: '/cases/$id'
      preLoaderRoute: typeof CasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/$id': {
      id: '/vendors/$id'
      path: '/vendors/$id'
      fullPath: '/vendors/$id'
      preLoaderRoute: typeof VendorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/': {
      id: '/worker/'
      path: '/worker'
      fullPath: '/worker/'
      preLoaderRoute: typeof WorkerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/submit': {
      id: '/worker/submit'
      path: '/worker/submit'
      fullPath: '/worker/submit'
      preLoaderRoute: typeof WorkerSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/case/$code': {
      id: '/worker/case/$code'
      path: '/worker/case/$code'
      fullPath: '/worker/case/$code'
      preLoaderRoute: typeof WorkerCaseCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssuranceRoute: AssuranceRoute,
  AuditRoute: AuditRoute,
  CredentialRoute: CredentialRoute,
  DashboardRoute: DashboardRoute,
  EvidenceRoute: EvidenceRoute,
  PackRoute: PackRoute,
  RemediationRoute: RemediationRoute,
  ResetRoute: ResetRoute,
  VerificationRoute: VerificationRoute,
  VerifyRoute: VerifyRoute,
  CasesIdRoute: CasesIdRoute,
  VendorsIdRoute: VendorsIdRoute,
  WorkerSubmitRoute: WorkerSubmitRoute,
  CasesIndexRoute: CasesIndexRoute,
  VendorsIndexRoute: VendorsIndexRoute,
  WorkerIndexRoute: WorkerIndexRoute,
  WorkerCaseCodeRoute: WorkerCaseCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
